### ISSUE TITLE
Tank Indicator

### ISSUE THREAD

**Issue by jDanek** [bdew-minecraft/pressure#81] opened 2016-10-16 21:06 UTC
I found a bug in the indication of the amount of liquid in the tank, the tank I sent 20000mB water are disconnected from the server (as well as on single player) and returning indicator shows the emptiness and even mod W.a.i.l.a writes 'Empty'! If you add or remove fluid indicator again show the expected state

**Comment by bdew** [comment] 2016-10-18 18:50
Hm i can't reproduce this, however i suspect this has something to do with a change i implemented to reduce needless chunk update spam.

Are you logging in near the tank or far away and then coming closer? Anything else special about your setup?

**Comment by jDanek** [comment] 2016-10-19 02:53
Nothing special, no matter whether you are standing at the tank, or to come near him. Until completion of insertion or withdrawal of fluids ... then updated

**Comment by bdew** [comment] 2017-10-12 16:49
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:49 UTC
