### ISSUE TITLE
Crash w/ IC2 Fluid Heat Exchanger

### ISSUE THREAD

**Issue by ghost** [bdew-minecraft/pressure#65] opened 2016-04-26 20:12 UTC
Sometimes (unable to 100% reliably reproduce the issue) when fluid transfer starts from an IC2 fluid reactor to a heat exchanger, and then back to the reactor, if Pressure Pipes is handling the fluid transfer using High Pressure Input/Output, the game crashes with the following exception:

http://pastebin.com/Bce2aruJ

IC2 build 820 Experimental (1.7.10)
BDLib 1.9.4.109
Pressure Pipes 1.2.5.125 (tested, bugged all the way to 1.3.0.131)

no other fluid handler causes this exception. Tested with Mekanism Mechanical Pipe, BuildCraft golden fluid pipe, BuildCraft Additional Objects Reinforced Golden Fluid Pipe (higher throughput), and even Gregtech's various fluid pipes. Only crashes with Pressure Pipes hooked up directly to the heat exchanger.

**Comment by bdew** [comment] 2016-04-27 06:49
I've tried playing with it a bit and couldn't reproduce the crash. What's your exact setup?

I've looked at the code in IC2 and it's completely stupid and really should handle stuff like that more gracefully, but i'm willing to work around it on my side if possible (and i can figure out how exactly it happens in the first place).

**Comment by ghost** [comment] 2016-04-28 05:07
Exact setup?

Fluid Reactor Fluid Port w/Fluid Ejector -> High Pressure Input -> High Pressure Pipe -> High Pressure Output x14 -> IC2 Fluid Heat Exchanger x14 with Fluid Ejector -> High Pressure Input x14 -> High Pressure Pipe -> High Pressure Output -> Fluid Reactor Fluid Port

I can't reliably make it happen. Just seems to do it whenever the hell it feels like it. It's damn near impossible to track down because the reactor can run for hours on end without an issue. Then seemingly out of nowhere, server & client crash with that exception about non-matching fill values.

Any idea how I could further narrow it down and/or trigger it?

I've double and triple checked my findings, and again tested with Mekanism Mechanical Pipe, GT Bronze/Steel/TungstenSteel Fluid Pipes, and BC/ABO Golden/Reinforced Golden fluid pipes.

If theres something I can do to help it trigger the exception in a repeatable way with Pressure pipes, I would LOVE to get this solved because your mod shits on every one of them in terms of utility. And it just looks badass <3

**Comment by bdew** [comment] 2016-04-28 07:03
> Any idea how I could further narrow it down and/or trigger it?

That's what i'm trying to figure out as well :P

>  IC2 Fluid Heat Exchanger x14 with Fluid Ejector -> High Pressure Input x14 -> High Pressure Pipe -> High Pressure Output -> Fluid Reactor Fluid Port

The problem is on this side of the chain. From looking at IC2 code and the crash report, it looks like something like that happens:
- Ejector is asking the pressure input how much fluid it can accept
- Pressure input says it can accept 36 mb
- Ejector tries to push 36 mb to the pressure input
- Pressure input only accepts 24 mb
- Ejector doesn't like that and decides to crash (instead of just keeping the leftover for the next time, like any sensible implementation would do)

The question is why does the pressure system claims it can accept 36mb while only accepting 24. It could be because of a bug in PP that i might be able to fix, or it could be because the reactor claims it can accept 36 while only accepting 24 (in which case it's not fixable on my side).

The other pipes provide some level of buffering, which likely makes that issue not happen.

I'm going to try recreating your setup and if i can get it to crash in a controllable envionment - see more closely what's going on.

As a workaround for now you could take out the ejector upgrades and switch the pressure inputs to powered mode (with redstone signal), or alternatively put some other kind of pipe between the heat exchangers and the pressure inputs to act as a buffer.

**Comment by ghost** [comment] 2016-04-28 15:40
Thanks BDew, I will remove the fluid ejector and instead (for now until you do your investimigations :P) use powered mode with a fluid filter (dont want it sucking out cold coolant >:) ) and see if this resolves it in the meantime. I hope we can narrow this down and get it all fixed up!

**Comment by bdew** [comment] 2017-10-12 16:46
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:46 UTC
