### ISSUE TITLE
Another fluid registry crash

### ISSUE THREAD

**Issue by NEXUS2345** [bdew-minecraft/pressure#36] opened 2015-04-04 14:46 UTC
We are not sure what is causing these crashes but it is also breaking Not Enough Items causing us to have to load a single player world before logging into our server (custom modpack)

http://pastebin.com/n1udrVCh
http://pastebin.com/DrRQQ6Mt

**Comment by NEXUS2345** [comment] 2015-04-04 21:11
@KingLemming maybe take a look at this also? Seeing as you are the master of fluids...

**Comment by bdew** [comment] 2015-04-05 07:06
So logging into a singleplayer world before going to multiplayer fixes it?  kinda confirms my suspicions that something weird is going on with the id map in Forge...

At any rate, please try this version: http://jenkins.bdew.net/job/pressure-1.7.10/88/artifact/build/libs/pressure-mc1710-1.1.1.88.jar

Also please post the full forge log after updating and logging to the server directly without going to SP. If it doesn't crash i want to look at the messages printed by my checks.

**Comment by bdew** [comment] 2015-04-05 07:07
Oh and it looks like you're running BDLib 1.7.0.68 which is a few builds below the current stable release (1.7.0.70) - please update that as well.

**Comment by NEXUS2345** [comment] 2015-04-05 10:40
This is the Forge log BEFORE updating to your given version: http://pastebin.com/TtN5VZgs
Just also thought I would let you know that we run Bungee Cord and Cauldron on the server, but it shouldn't be causing this I believe.

**Comment by NEXUS2345** [comment] 2015-04-05 11:06
Also, we have updated to BDLib 1.7.0.70 and the issue is still present. We will be trying the new PressurePipes build soon.

**Comment by bdew** [comment] 2015-04-06 08:11
Looks like the forge 10.13.3.1355 changes a bunch of code that might be related to this issue. If anyone feels adventurous - grab [this build](http://jenkins.bdew.net/job/pressure-1.7.10/89/) and try it with the new forge.

Still interested in whether the previous fix did anything and looking at any logfiles with that version.

**Comment by NEXUS2345** [comment] 2015-04-06 17:10
Forge log with both updated (BDLib build 70 and PressurePipes build 88): http://pastebin.com/CJzfgdJk

Sorry about it being incomplete but Technic launcher is stupid...

**Comment by bdew** [comment] 2015-04-06 17:16
Interesting. I'm not sure what's up with that, do you by chance have a mod installed on the client that isn't on the server? Or config differences? I also wonder if that change in forge would affect that.

I assume the crash / NEI not loading is fixed now? If so then this is as much fixed as i can from my side of things and this issue can be closed.

```
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'cablingcolophony' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'fairy.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'limemilk' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'osmiumtetroxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'osmium.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'nitrogen' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'sulfuricanhydride' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.nickelsulfate' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'air' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'fluidrubbertreesap' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.bronze' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'pokefennium.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.gold' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'spruceresin' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'liquidglass' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'acetylene' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.bluevitriol' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.natriumhydroxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'aquaregia' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'refined.glowstone.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'vapour.sulfuricacid' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.steel' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'nitricacid' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'glyceryl' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'sodiumperoxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.rubberwithsulfur' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'cablingcolophony' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'fairy.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'limemilk' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'osmiumtetroxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'osmium.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'nitrogen' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'sulfuricanhydride' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.nickelsulfate' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'air' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'fluidrubbertreesap' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.bronze' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'pokefennium.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.gold' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'spruceresin' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'liquidglass' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'acetylene' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.bluevitriol' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'solution.natriumhydroxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'aquaregia' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'refined.glowstone.molten' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'vapour.sulfuricacid' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.steel' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'nitricacid' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'glyceryl' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'sodiumperoxide' is not registered after returning it from getRegisteredFluids
[B#296]  [18:10:07] [Client thread/ERROR] [pressure]: Forge claims fluid 'molten.rubberwithsulfur' is not registered after returning it from getRegisteredFluids
```

It also looks like NEI Integration fails to load as well, with a very similar error:

```
[B#296]  [18:10:12] [Client thread/ERROR] [NotEnoughItems]: Failed to Load tonius.neiintegration.NEIIntegrationConfig
[B#296]  java.lang.NullPointerException
[B#296]         at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:119) ~[FluidRegistry.class:?]
```

**Comment by NEXUS2345** [comment] 2015-04-06 17:18
Yes, the issue with NEI is now fixed, however, yes, there are config differences between the server and client.

**Comment by bdew** [comment] 2015-04-06 17:21
Well then i guess that's the root cause. The fluid id map is different and forge doesn't sync up everything properly. I'm closing this as i don't see anything more i can do except preventing it from outright crashing and complaining in the logs.

**Closed as completed by bdew** 2015-04-06 17:21 UTC
