### ISSUE TITLE
[1.10.2] Block State crash

### ISSUE THREAD

**Issue by YOYOK9** [bdew-minecraft/pressure#96] opened 2017-03-24 03:58 UTC
When teleporting back to base the server crashed with and gave this report:
http://pastebin.com/wLjYwy5F

pressure-1.3.1.25-mc1.10.2
forge-1.10.2-12.18.3.2239

**Comment by bdew** [comment] 2017-03-28 06:26
Duplicate of #97

**Closed as completed by bdew** 2017-03-28 06:26 UTC
