### ISSUE TITLE
[High] Cannot get property Property Direction

### ISSUE THREAD

**Issue by YOYOK9** [bdew-minecraft/pressure#97] opened 2017-03-27 20:03 UTC
Have been having troubles recently with pressure pipes causing the server to crash when trying to pull gas(mekanism) or fluids out of a tank. After looking at the reports it seems the some of the blocks when unloaded have difficulty finding what direction they were facing (i think) 

We really enjoy pressure pipes and really do not want to have to remove it!

Versions:
bdlib-1.12.4.24-mc1.10.2
pressure-1.3.1.25-mc1.10.2
forge-1.10.2-12.18.3.2239
mc: 1.10.2

Crash report: 
https://pastebin.com/HumKdmpF

**Comment by bdew** [comment] 2017-03-28 06:34
First of all please don't post multiple reports for the same issue...

Second, that crash doesn't make a whole lot of sense to me. It looks like there's a Pressure Pipes TE somewhere without the block existing (the block is air). It might be a result of another mod doing something weird or some weird bug.

From your 2 crashes it looks like 2 different networks having the same problem...

* -1534,122,-1535 
* 1196,75,-2209

Those are the coordinates of some block on that network, but it's not the block that causes the crash.

Can you give me more details on what's going on there? Also are this areas chunkloaded?

**Comment by YOYOK9** [comment] 2017-03-28 21:23
Sorry didn't realize they were the same issue (my bad). 
The areas are not chunk loaded and i believe a player was using them to push or pull oxygen gas out of a mekanism machine.

**Comment by bdew** [comment] 2017-03-29 05:47
I tried reproducing it but was not able, and as i said the crash doesn't make much sense to me. Can you provide more details about the setup? I need more info to figure out how it breaks.

**Comment by YOYOK9** [comment] 2017-03-29 23:33
Alright have more info on what's happening. So little back story: We have learned with pressure pipes that you can convert mekanisms gas to liquid form by passing it through the tank from your mod and vice versa.

What a player was trying to do was take oxygen out of the separator with gas inputs and insert it into a block from advanced rocketry with a fluid output. though without the tank, 
pic: (Orange wool marks gas inputs)
https://puu.sh/v2Mys/5abe9b642b.jpg

Player quote
> when you deload the area (Exit the DIM or just fly away) coming back seems to crash the server
so it's something to do when loading them back up

 The server is also using sponge forge (if that helps)

**Comment by bdew** [comment] 2017-10-12 16:52
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:52 UTC
