### ISSUE TITLE
Server Crash on Mining Pressure Pipes Block

### ISSUE THREAD

**Issue by Keridos** [bdew-minecraft/pressure#86] opened 2016-11-12 07:47 UTC
This happened on v1.3.1.18 on Forge 12.18.2.2122 when mining a pressure pipe intake or outlet with a TInkers Construct Pickaxe. (Doubt the pickaxe has any effect on this though): https://paste.ee/p/hVsu1

Might be related to #85 .

**Comment by Keridos** [comment] 2016-11-12 08:13
Might be related to #85 .

**Comment by bdew** [comment] 2016-11-12 21:54
I can't reproduce neither this nor #85.

The errors look like there is some confusion going on between tile entities and actual blocks. Like the TE isn't removed when the block is and crashes when it tries to get properties from the blockstate. This is really weird, i'm wonder if it's one of the coremods causing shenanigans...

Does it happen consistently or was that a one-off thing?

**Comment by Keridos** [comment] 2016-11-13 10:02
Happens consistently.

**Comment by bdew** [comment] 2017-10-12 16:51
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:51 UTC
