### ISSUE TITLE
[REQUEST] Gas Input/Output for Mekanism 9.x

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/pressure#71] opened 2016-08-13 16:18 UTC
Hello! I love your mod and have used it prior. Our server recently went to 1.10.2 so we are using Mekanism 9.x and... sadly I noticed the gas pieces for tanks are no longer there! I used the heck out of that in Mek 8.x as your tanks were vastly superior to anything Mek had. :)

Would love to see them back!

Cheers

**Comment by bdew** [comment] 2016-08-14 07:20
Planned, soon(tm).

**Comment by Utildayael** [comment] 2016-08-14 14:29
Yay! :)

**Comment by bdew** [comment] 2016-08-14 21:09
Will be in the next alpha build

**Closed as completed** 2016-08-14 21:09 UTC

**Comment by Utildayael** [comment] 2016-08-14 22:43
Thanks Bdew. You're super fast!!

**Comment by Silke-Smoothe** [comment] 2016-11-17 17:01
Pressure Pipes 1.3.1.18
Mekanism 9.2.0
MC1.10.2

Multiple instances and multiple created worlds, about 140 other mods.
JEI shows the Pressurized Gas Inputs/Outputs, but has no crafting recipe for them.
When given the item through creative/cheat mode, the items work as intended. But there is no way to craft them without cheating them in.
